{
 "title": "SonarQube KPI Dashboard",
 "description": "SonarQube KPI Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_key",
    "label": "project_key",
    "query": "import \"influxdata/influxdb/schema\"\nschema.measurements(bucket: \"sonarqube_kpi\")\n"
   },
   {
    "name": "branch",
    "label": "branch",
    "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"branch_name\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Quality Gate Status",
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"branch_name\"] == \"${branch}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"alert_status\")\n  |> last()\n  |> keep(columns: [\"_value\"])\n"
    }
   ]
  },
  {
   "title": "Issue Result",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true
  },
  {
   "title": "Frequency of Rule",
   "type": "barchart",
   "description": "show only 10 common rule",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"branch_name\"] == \"${branch}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rule-id\")\n  |> unique(column: \"_value\")\n  |> group(columns: [\"rule\"])\n  |> count(column: \"key\")\n  |> group()\n  |> limit(n:10, offset: 0)\n"
    }
   ]
  },
  {
   "title": "Severity Issue",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"branch_name\"] == \"${branch}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"blocker_violations\" or r[\"_field\"] == \"critical_violations\" or r[\"_field\"] == \"info_violations\" or r[\"_field\"] == \"major_violations\" or r[\"_field\"] == \"minor_violations\")\n  |> unique(column: \"_field\")\n  |> group(columns: [\"metric\"])\n  |> toInt()\n  |> sum(column: \"_value\")\n  |> group()"
    }
   ]
  },
  {
   "title": "Resolution Issue",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"branch_name\"] == \"${branch}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"confirmed_issues\" or r[\"_field\"] == \"false_positive_issues\" or r[\"_field\"] == \"open_issues\" or r[\"_field\"] == \"reopened_issues\")\n  |> unique(column: \"_field\")\n  |> group(columns: [\"metric\"])\n  |> toInt()\n  |> sum(column: \"_value\")\n  |> group()"
    }
   ]
  },
  { "title": "Test Result", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Line Of Code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ncloc\")\n  |> filter(fn: (r) => r[\"branch_name\"] == \"${branch}\")\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> toInt()\n  |> sum()"
    }
   ]
  },
  {
   "title": "Number of unit test",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"branch_name\"] == \"${branch}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tests\")\n  |> last()\n  |> unique(column: \"_time\")\n  |> group(columns: [\"_time\"])\n  |> toInt()\n  |> sum()\n"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"coverage\")\n  |> filter(fn: (r) => r[\"branch_name\"] == \"${branch}\")\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> toFloat()\n  |> sum()"
    }
   ]
  },
  {
   "title": "Log Issue",
   "type": "logs",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"branch_name\"] == \"${branch}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rule-id\")\n  |> unique(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Duplicated Lines Density",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"duplicated_lines_density\")\n  |> filter(fn: (r) => r[\"branch_name\"] == \"master\")\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> toFloat()\n  |> sum()"
    }
   ]
  },
  {
   "title": "Duplications",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"duplicated_lines\")\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> group()\n  |> toFloat()\n  |> sum()\n  |> map(fn: (r) => ({ \"Duplicated Lines\": r._value}) )"
    },
    {
     "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"duplicated_files\")\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> group()\n  |> toFloat()\n  |> sum()\n  |> map(fn: (r) => ({ \"Duplicated Files\": r._value}) )"
    },
    {
     "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"duplicated_blocks\")\n  |> last()\n  |> group(columns: [\"_time\"])\n  |> group()\n  |> toFloat()\n  |> sum()\n  |> map(fn: (r) => ({ \"Duplicated Blocks\": r._value}) )"
    }
   ]
  },
  {
   "title": "Scan History ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"sonarqube_kpi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${project_key}\")\n  |> filter(fn: (r) => r[\"branch_name\"] == \"${branch}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\n  |> unique(column: \"_value\")"
    }
   ]
  }
 ]
}